### ISSUE TITLE
Convert order id to okey

### ISSUE THREAD

**Issue by StanZhuravlev** [kinderly/axiomus_api#5]
Hi!

How I can convert order id (ex. 5453755) to okey (ex. fbe9c5b7b98ec639df6a5ad5e8db1111)? In Axiomus API for it used get_okey method, but as understanf, AxiomusApi don't support it? 

What's best way do it? 

Best,
Stan

**Comment by zsand** [comment]
Hi, Stan!

I don't know how to do it using api, you can address this question to the axiomus support,  but in our practice it's not necessary, you get okey when you create an order, in some rare cases you can e-mail to the axiomus support to get  okey ids for certain orders.

**Comment by StanZhuravlev** [comment]
Thank you, but I have another task - make a dashboard of order statuses. User can see a order id in Axiomus Private Cabinete, and add to local system (online store). But user can't show okey. :( 

In last version, Axiomus have a new method:

Запрос ключей заявок (метод get_okey)
Метод позволяет получить ключи (okey) заявок на основе номеров заявок.
```
<?xml version='1.0' standalone='yes'?>
<singleorder>
<mode>get_okey</mode>
<auth ukey="XXcd208495d565ef66e7dff9f98764XX" />
<orders>
    <order>6158506</order>
    <order>6157524</order>
</orders>
</singleorder>

```
But can you gem execute this method in any way? 

Best,
Stan

**Comment by StanZhuravlev** [comment]
Ok, I'm Inherite own classes around AxiomusApi, and task is done. :)
